### ISSUE TITLE
Login Issue

### ISSUE THREAD

**Issue by dmpiq** [dmpiq/piq#1]
@pkondratko I get an error trying to log in via index12.php since the last update. "Warning: mysqli_num_rows() expects parameter 1 to be mysqli_result, boolean given in C:\xampp\htdocs\piq\login.php on line 26"

**Comment by pkondratko** [comment]
Will look.

**Comment by pkondratko** [comment]
Logged in here OK.  I modified the user table a while ago, on my set of files. Pretty sure your's wont be the same:


Column	Type	Null	Default	Comments	MIME
id_user	int(11)	No 	 	 	 
username	varchar(32)	No 	 	 	 
password	varchar(100)	No 	 	 	 
created_date	datetime	No 	 	 	 
first_name	varchar(32)	No 	 	 	 
last_name	varchar(32)	No 	 	 	 
company_name	varchar(50)	No 	 	 	 
user_class	int(1)	No 	 	 	 


The company name was because I wasn't sure how the 'signup.php' file was going to mesh with the 'login.php' file, so I was trying things out.  User class is to hold what user they are ( i have 1, 2, 3 for now ).  Modify those two ( i think it's just those two ) and it should be right.  We can discuss further the merits / costs of how we are going to handle signup / login, but I feel our access control should be defined first, then adjust the login & signup to match.

**Comment by dmpiq** [comment]
I made the updates to the DB structure and made all the users class 1.  It's not working right now because after login it directs me to localhost/index12.php (where the real path is localhost/piq/index12php.)I remember you said there was something in there about linux and file locations, is this the source of the problem?It's not really that critical for me right now because I can work on datatables stuff in the testtabsindex.DMOn May 10, 2015 at 6:05 PM pkondratko <notifications@github.com> wrote:Logged in here OK. I modified the user table a while ago, on my set of files. Pretty sure your's wont be the same:Column Type Null Default Comments MIME id_user int(11) No username varchar(32) No password varchar(100) No created_date datetime No first_name varchar(32) No last_name varchar(32) No company_name varchar(50) No user_class int(1) NoThe company name was because I wasn't sure how the 'signup.php' file was going to mesh with the 'login.php' file, so I was trying things out. User class is to hold what user they are ( i have 1, 2, 3 for now ). Modify those two ( i think it's just those two ) and it should be right. We can discuss further the merits / costs of how we are going to handle signup / login, but I feel our access control should be defined first, then adjust the login & signup to match.—Reply to this email directly or view it on GitHub.
